-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MATE_HDLsolver_myFirstCircuit\Counter_Free_Running.vhd
-- Created: 2026-03-23 17:18:12
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Counter_Free_Running
-- Source Path: MATE_HDLsolver_myFirstCircuit/ForFPGA/Counter Free-Running
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Counter_Free_Running IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_166_0                       :   IN    std_logic;
        y                                 :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
        );
END Counter_Free_Running;


ARCHITECTURE rtl OF Counter_Free_Running IS

  -- Component Declarations
  COMPONENT Increment_Real_World
    PORT( u                               :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          y                               :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
          );
  END COMPONENT;

  COMPONENT Wrap_To_Zero
    PORT( U                               :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          Y                               :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Increment_Real_World
    USE ENTITY work.Increment_Real_World(rtl);

  FOR ALL : Wrap_To_Zero
    USE ENTITY work.Wrap_To_Zero(rtl);

  -- Signals
  SIGNAL Output_out1                      : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Increment_Real_World_out1        : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL Wrap_To_Zero_out1                : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL Wrap_To_Zero_out1_unsigned       : unsigned(3 DOWNTO 0);  -- ufix4

BEGIN
  u_Increment_Real_World : Increment_Real_World
    PORT MAP( u => std_logic_vector(Output_out1),  -- ufix4
              y => Increment_Real_World_out1  -- ufix4
              );

  u_Wrap_To_Zero : Wrap_To_Zero
    PORT MAP( U => Increment_Real_World_out1,  -- ufix4
              Y => Wrap_To_Zero_out1  -- ufix4
              );

  Wrap_To_Zero_out1_unsigned <= unsigned(Wrap_To_Zero_out1);

  Output_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Output_out1 <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_166_0 = '1' THEN
        Output_out1 <= Wrap_To_Zero_out1_unsigned;
      END IF;
    END IF;
  END PROCESS Output_process;


  y <= std_logic_vector(Output_out1);

END rtl;

