-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MATE_HDLsolver_myFirstCircuit\Discrete.vhd
-- Created: 2026-03-23 17:18:12
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Discrete
-- Source Path: MATE_HDLsolver_myFirstCircuit/ForFPGA/PWM Generator/Discrete Triangular-Waveform Generator/Set-Reset 
-- Flip-Flop/Discret
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Discrete IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_166_0                       :   IN    std_logic;
        Set                               :   IN    std_logic;
        Reset_1                           :   IN    std_logic;
        Q                                 :   OUT   std_logic
        );
END Discrete;


ARCHITECTURE rtl OF Discrete IS

  -- Signals
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Unit_Delay_out1                  : std_logic;
  SIGNAL Logical_Operator5_out1           : std_logic;
  SIGNAL Logical_Operator4_out1           : std_logic;
  SIGNAL Switch_out1                      : std_logic;
  SIGNAL Logical_Operator2_out1           : std_logic;
  SIGNAL Logical_Operator1_out1           : std_logic;

BEGIN
  Constant_out1 <= '1';

  Logical_Operator_out1 <=  NOT Reset_1;

  Logical_Operator5_out1 <= Logical_Operator_out1 AND Unit_Delay_out1;

  Logical_Operator4_out1 <= Set OR Logical_Operator5_out1;

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_166_0 = '1' THEN
        Unit_Delay_out1 <= Switch_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  Logical_Operator2_out1 <= Set OR Unit_Delay_out1;

  Logical_Operator1_out1 <= Logical_Operator2_out1 AND Logical_Operator_out1;

  
  Switch_out1 <= Logical_Operator1_out1 WHEN Constant_out1 = '0' ELSE
      Logical_Operator4_out1;

  Q <= Switch_out1;

END rtl;

