-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MATE_HDLsolver_myFirstCircuit\Discrete_Triangular_Waveform_Generator.vhd
-- Created: 2026-03-23 17:18:12
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Discrete_Triangular_Waveform_Generator
-- Source Path: MATE_HDLsolver_myFirstCircuit/ForFPGA/PWM Generator/Discrete Triangular-Waveform Generator
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Discrete_Triangular_Waveform_Generator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_166_0                       :   IN    std_logic;
        enb_1_166_1                       :   IN    std_logic;
        enb                               :   IN    std_logic;
        steps                             :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Triangle                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
        );
END Discrete_Triangular_Waveform_Generator;


ARCHITECTURE rtl OF Discrete_Triangular_Waveform_Generator IS

  -- Component Declarations
  COMPONENT Set_Reset_Flip_Flop
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_166_0                     :   IN    std_logic;
          Set                             :   IN    std_logic;
          Reset_1                         :   IN    std_logic;
          Q                               :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT nfp_convert_sfix_32_En0_to_single
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in                          :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT nfp_convert_fix_16_En0_to_single
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in                          :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT nfp_div_single
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Set_Reset_Flip_Flop
    USE ENTITY work.Set_Reset_Flip_Flop(rtl);

  FOR ALL : nfp_convert_sfix_32_En0_to_single
    USE ENTITY work.nfp_convert_sfix_32_En0_to_single(rtl);

  FOR ALL : nfp_convert_fix_16_En0_to_single
    USE ENTITY work.nfp_convert_fix_16_En0_to_single(rtl);

  FOR ALL : nfp_div_single
    USE ENTITY work.nfp_div_single(rtl);

  -- Signals
  SIGNAL steps_unsigned                   : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Simulink_PS_Converter1           : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Shift_Arithmetic_out1            : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Simulink_PS_Converter1_1         : signed(31 DOWNTO 0);  -- int32
  SIGNAL Gain2_cast                       : signed(63 DOWNTO 0);  -- sfix64
  SIGNAL Gain2_out1                       : signed(31 DOWNTO 0);  -- int32
  SIGNAL Constat1_out1                    : signed(31 DOWNTO 0);  -- int32
  SIGNAL Constat_out1                     : signed(31 DOWNTO 0);  -- int32
  SIGNAL Sum2_out1                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL Sum2_out1_1                      : signed(31 DOWNTO 0);  -- int32
  SIGNAL Unit_Delay1_bypass_reg           : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL Unit_Delay1_out1                 : signed(31 DOWNTO 0);  -- int32
  SIGNAL Unit_Delay1_out1_1               : signed(31 DOWNTO 0);  -- int32
  SIGNAL Relational_Operator2_out1        : std_logic;
  SIGNAL Set_Reset_Flip_Flop_bypass_reg   : std_logic;  -- ufix1
  SIGNAL Relational_Operator2_out1_1      : std_logic;
  SIGNAL Relational_Operator1_out1        : std_logic;
  SIGNAL Set_Reset_Flip_Flop1_bypass_reg  : std_logic;  -- ufix1
  SIGNAL Relational_Operator1_out1_1      : std_logic;
  SIGNAL Set_Reset_Flip_Flop_out1         : std_logic;
  SIGNAL Unit_Delay2_out1                 : std_logic;
  SIGNAL Unit_Delay2_out1_1               : std_logic;
  SIGNAL Switch_out1                      : signed(31 DOWNTO 0);  -- int32
  SIGNAL Sum2_add_temp                    : signed(32 DOWNTO 0);  -- sfix33
  SIGNAL Simulink_PS_Converter1_timer     : std_logic;
  SIGNAL delayMatch_reg                   : std_logic_vector(5 DOWNTO 0);  -- ufix1 [6]
  SIGNAL Simulink_PS_Converter1_timer_1   : std_logic;
  SIGNAL Simulink_PS_Converter1_default   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Data_Type_Conversion7_out1       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Simulink_PS_Converter1_2         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Simulink_PS_Converter1_zp        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Divide_out1                      : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_Set_Reset_Flip_Flop2 : Set_Reset_Flip_Flop
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_166_0 => enb_1_166_0,
              Set => Relational_Operator1_out1_1,
              Reset_1 => Relational_Operator2_out1_1,
              Q => Set_Reset_Flip_Flop_out1
              );

  u_MATE_HDLsolver_myFirstCircuit_ForFPGA_PWM_Generator_Discrete_Triangular_Waveform_Generator_nfp_convert_sfix_32_En0_to_single : nfp_convert_sfix_32_En0_to_single
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in => std_logic_vector(Sum2_out1),  -- int32
              nfp_out => Data_Type_Conversion7_out1  -- single
              );

  u_MATE_HDLsolver_myFirstCircuit_ForFPGA_PWM_Generator_Discrete_Triangular_Waveform_Generator_nfp_convert_fix_16_En0_to_single : nfp_convert_fix_16_En0_to_single
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in => std_logic_vector(Shift_Arithmetic_out1),  -- uint16
              nfp_out => Simulink_PS_Converter1_2  -- single
              );

  u_nfp_div_comp : nfp_div_single
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in1 => Data_Type_Conversion7_out1,  -- single
              nfp_in2 => Simulink_PS_Converter1_zp,  -- single
              nfp_out => Divide_out1  -- single
              );

  steps_unsigned <= unsigned(steps);

  Simulink_PS_Converter1 <= steps_unsigned;

  Shift_Arithmetic_out1 <= SHIFT_RIGHT(Simulink_PS_Converter1, 2);

  Simulink_PS_Converter1_1 <= signed(resize(Shift_Arithmetic_out1, 32));

  Gain2_cast <= resize( - (resize(Simulink_PS_Converter1_1, 33)), 64);
  
  Gain2_out1 <= X"7FFFFFFF" WHEN (Gain2_cast(63) = '0') AND (Gain2_cast(62 DOWNTO 31) /= X"00000000") ELSE
      X"80000000" WHEN (Gain2_cast(63) = '1') AND (Gain2_cast(62 DOWNTO 31) /= X"FFFFFFFF") ELSE
      Gain2_cast(31 DOWNTO 0);

  Constat1_out1 <= to_signed(1, 32);

  Constat_out1 <= to_signed(-1, 32);

  crp_out_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Sum2_out1_1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Sum2_out1_1 <= Sum2_out1;
      END IF;
    END IF;
  END PROCESS crp_out_delay_process;


  Unit_Delay1_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay1_bypass_reg <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_166_1 = '1' THEN
        Unit_Delay1_bypass_reg <= Sum2_out1_1;
      END IF;
    END IF;
  END PROCESS Unit_Delay1_bypass_process;

  
  Unit_Delay1_out1 <= Sum2_out1_1 WHEN enb_1_166_1 = '1' ELSE
      Unit_Delay1_bypass_reg;

  Unit_Delay1_out1_1 <= Unit_Delay1_out1;

  
  Relational_Operator2_out1 <= '1' WHEN Sum2_out1 < Gain2_out1 ELSE
      '0';

  Set_Reset_Flip_Flop_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Set_Reset_Flip_Flop_bypass_reg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_166_1 = '1' THEN
        Set_Reset_Flip_Flop_bypass_reg <= Relational_Operator2_out1;
      END IF;
    END IF;
  END PROCESS Set_Reset_Flip_Flop_bypass_process;

  
  Relational_Operator2_out1_1 <= Relational_Operator2_out1 WHEN enb_1_166_1 = '1' ELSE
      Set_Reset_Flip_Flop_bypass_reg;

  
  Relational_Operator1_out1 <= '1' WHEN Sum2_out1 >= Simulink_PS_Converter1_1 ELSE
      '0';

  Set_Reset_Flip_Flop1_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Set_Reset_Flip_Flop1_bypass_reg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_166_1 = '1' THEN
        Set_Reset_Flip_Flop1_bypass_reg <= Relational_Operator1_out1;
      END IF;
    END IF;
  END PROCESS Set_Reset_Flip_Flop1_bypass_process;

  
  Relational_Operator1_out1_1 <= Relational_Operator1_out1 WHEN enb_1_166_1 = '1' ELSE
      Set_Reset_Flip_Flop1_bypass_reg;

  Unit_Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay2_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_166_0 = '1' THEN
        Unit_Delay2_out1 <= Set_Reset_Flip_Flop_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay2_process;


  Unit_Delay2_out1_1 <= Unit_Delay2_out1;

  
  Switch_out1 <= Constat1_out1 WHEN Unit_Delay2_out1_1 = '0' ELSE
      Constat_out1;

  Sum2_add_temp <= resize(Switch_out1, 33) + resize(Unit_Delay1_out1_1, 33);
  
  Sum2_out1 <= X"7FFFFFFF" WHEN (Sum2_add_temp(32) = '0') AND (Sum2_add_temp(31) /= '0') ELSE
      X"80000000" WHEN (Sum2_add_temp(32) = '1') AND (Sum2_add_temp(31) /= '1') ELSE
      Sum2_add_temp(31 DOWNTO 0);

  Simulink_PS_Converter1_timer <= '1';

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg(0) <= Simulink_PS_Converter1_timer;
        delayMatch_reg(5 DOWNTO 1) <= delayMatch_reg(4 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  Simulink_PS_Converter1_timer_1 <= delayMatch_reg(5);

  Simulink_PS_Converter1_default <= X"3f800000";

  
  Simulink_PS_Converter1_zp <= Simulink_PS_Converter1_default WHEN Simulink_PS_Converter1_timer_1 = '0' ELSE
      Simulink_PS_Converter1_2;

  Triangle <= Divide_out1;

END rtl;

