-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MATE_HDLsolver_myFirstCircuit\ForFPGA_tc.vhd
-- Created: 2026-03-23 17:18:12
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ForFPGA_tc
-- Source Path: ForFPGA_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_166_0 : 166x slower than clk with last phase
-- enb_1_166_1 : 166x slower than clk with phase 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ForFPGA_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_166_0                       :   OUT   std_logic;
        enb_1_166_1                       :   OUT   std_logic
        );
END ForFPGA_tc;


ARCHITECTURE rtl OF ForFPGA_tc IS

  -- Signals
  SIGNAL count166                         : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL comp_0_tmp                       : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL enb_1_166_0_1                    : std_logic;
  SIGNAL comp_1_tmp                       : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL enb_1_166_1_1                    : std_logic;

BEGIN
  enb <= clk_enable;

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 165
  counter_166_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      count166 <= to_unsigned(16#01#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF count166 >= to_unsigned(16#A5#, 8) THEN 
          count166 <= to_unsigned(16#00#, 8);
        ELSE 
          count166 <= count166 + to_unsigned(16#01#, 8);
        END IF;
      END IF;
    END IF;
  END PROCESS counter_166_process;


  
  comp_0_tmp <= '1' WHEN count166 = to_unsigned(16#A5#, 8) ELSE
      '0';

  phase_0_tmp <= comp_0_tmp AND clk_enable;

  phase_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_0 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_process;


  enb_1_166_0_1 <= phase_0 AND clk_enable;

  enb_1_166_0 <= enb_1_166_0_1;

  
  comp_1_tmp <= '1' WHEN count166 = to_unsigned(16#00#, 8) ELSE
      '0';

  phase_1_tmp <= comp_1_tmp AND clk_enable;

  phase_delay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_1 <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_1_process;


  enb_1_166_1_1 <= phase_1 AND clk_enable;

  enb_1_166_1 <= enb_1_166_1_1;

END rtl;

