vlib work
vmap -c
vcom  ForFPGA_pkg.vhd
vcom  ForFPGA_tc.vhd
vcom  Increment_Real_World.vhd
vcom  Wrap_To_Zero.vhd
vcom  Counter_Free_Running.vhd
vcom  Discrete.vhd
vcom  Set_Reset_Flip_Flop.vhd
vcom  nfp_convert_fix_16_En0_to_single.vhd
vcom  nfp_convert_sfix_32_En0_to_single.vhd
vcom  nfp_div_single.vhd
vcom  Discrete_Triangular_Waveform_Generator.vhd
vcom  nfp_relop_single.vhd
vcom  PWM_Generator.vhd
vcom  Compare_To_Constant.vhd
vcom  nfp_uminus_single.vhd
vcom  nfp_mul_single.vhd
vcom  nfp_sub_single.vhd
vcom  LC_vectorized.vhd
vcom  nfp_add_single.vhd
vcom  ForFPGA.vhd
