-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MATE_HDLsolver_myFirstCircuit\Increment_Real_World.vhd
-- Created: 2026-03-23 17:18:12
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Increment_Real_World
-- Source Path: MATE_HDLsolver_myFirstCircuit/ForFPGA/Counter Free-Running/Increment Real World
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Increment_Real_World IS
  PORT( u                                 :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        y                                 :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
        );
END Increment_Real_World;


ARCHITECTURE rtl OF Increment_Real_World IS

  -- Signals
  SIGNAL u_unsigned                       : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL FixPt_Constant_out1              : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL FixPt_Sum1_out1                  : unsigned(3 DOWNTO 0);  -- ufix4

BEGIN
  u_unsigned <= unsigned(u);

  FixPt_Constant_out1 <= to_unsigned(16#1#, 4);

  FixPt_Sum1_out1 <= resize(resize(u_unsigned, 32) + resize(FixPt_Constant_out1, 32), 4);

  y <= std_logic_vector(FixPt_Sum1_out1);

END rtl;

