-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MATE_HDLsolver_myFirstCircuit\LC_vectorized.vhd
-- Created: 2026-03-23 17:18:12
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LC_vectorized
-- Source Path: MATE_HDLsolver_myFirstCircuit/ForFPGA/LC vectorized
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ForFPGA_pkg.ALL;

ENTITY LC_vectorized IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_166_1                       :   IN    std_logic;
        enb                               :   IN    std_logic;
        gate                              :   IN    std_logic_vector(4 DOWNTO 0);  -- boolean [5]
        minus_g                           :   IN    vector_of_std_logic_vector32(0 TO 4);  -- single [5]
        x                                 :   IN    std_logic_vector(4 DOWNTO 0);  -- boolean [5]
        Xin_idx                           :   IN    vector_of_std_logic_vector16(0 TO 4);  -- uint16 [5]
        vi_in                             :   IN    vector_of_std_logic_vector32(0 TO 4);  -- single [5]
        Hist                              :   OUT   vector_of_std_logic_vector32(0 TO 4)  -- single [5]
        );
END LC_vectorized;


ARCHITECTURE rtl OF LC_vectorized IS

  -- Component Declarations
  COMPONENT nfp_mul_single
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT nfp_uminus_single
    PORT( nfp_in                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT nfp_sub_single
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : nfp_mul_single
    USE ENTITY work.nfp_mul_single(rtl);

  FOR ALL : nfp_uminus_single
    USE ENTITY work.nfp_uminus_single(rtl);

  FOR ALL : nfp_sub_single
    USE ENTITY work.nfp_sub_single(rtl);

  -- Signals
  SIGNAL x_1                              : std_logic_vector(4 DOWNTO 0);  -- boolean [5]
  SIGNAL delayMatch1_reg                  : std_logic_vector(119 DOWNTO 0);  -- ufix1 [120]
  SIGNAL x_2                              : std_logic_vector(4 DOWNTO 0);  -- boolean [5]
  SIGNAL gate_1                           : std_logic_vector(4 DOWNTO 0);  -- boolean [5]
  SIGNAL Unit_Delay6_bypass_reg           : std_logic_vector(4 DOWNTO 0);  -- ufix1 [5]
  SIGNAL Unit_Delay6_out1                 : std_logic_vector(4 DOWNTO 0);  -- boolean [5]
  SIGNAL Unit_Delay6_out1_1               : std_logic_vector(4 DOWNTO 0);  -- boolean [5]
  SIGNAL delayMatch_reg                   : std_logic_vector(119 DOWNTO 0);  -- ufix1 [120]
  SIGNAL Unit_Delay6_out1_2               : std_logic_vector(4 DOWNTO 0);  -- boolean [5]
  SIGNAL Relational_Operator1_out1        : std_logic_vector(4 DOWNTO 0);  -- boolean [5]
  SIGNAL Logical_Operator_out1            : std_logic_vector(4 DOWNTO 0);  -- boolean [5]
  SIGNAL Logical_Operator_out1_0          : std_logic;
  SIGNAL gate_0                           : std_logic;
  SIGNAL minus_g_1                        : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL minus_g_2                        : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Divide_out1                      : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Divide_out1_0                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL gate_1_1                         : std_logic;
  SIGNAL Divide_out1_1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL gate_2                           : std_logic;
  SIGNAL Divide_out1_2                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL gate_3                           : std_logic;
  SIGNAL Divide_out1_3                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL gate_4                           : std_logic;
  SIGNAL Divide_out1_4                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Xin_idx_unsigned                 : vector_of_unsigned16(0 TO 4);  -- uint16 [5]
  SIGNAL Xin_idx_1                        : vector_of_unsigned16(0 TO 4);  -- uint16 [5]
  SIGNAL Xin_idx_0                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL gate_0_1                         : std_logic;
  SIGNAL Divide_out1_0_1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL gate_1_2                         : std_logic;
  SIGNAL Divide_out1_1_1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL gate_2_1                         : std_logic;
  SIGNAL Divide_out1_2_1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL gate_3_1                         : std_logic;
  SIGNAL Divide_out1_3_1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL gate_4_1                         : std_logic;
  SIGNAL Divide_out1_4_1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Xin_idx_1_1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Xin_idx_2                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Xin_idx_3                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Xin_idx_4                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Logical_Operator_out1_1          : std_logic;
  SIGNAL Logical_Operator_out1_2          : std_logic;
  SIGNAL Logical_Operator_out1_3          : std_logic;
  SIGNAL Logical_Operator_out1_4          : std_logic;
  SIGNAL From1_out1                       : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL From1_out1_4                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Unit_Delay1_out1                 : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Unit_Delay1_out1_4               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch5_out1_4                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL From1_out1_3                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Unit_Delay1_out1_3               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch5_out1_3                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL From1_out1_2                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Unit_Delay1_out1_2               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch5_out1_2                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL From1_out1_1                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Unit_Delay1_out1_1               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch5_out1_1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Unit_Delay5_out1                 : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Selector_out1_4                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Selector_out1_3                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Selector_out1_2                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Selector_out1_1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Gain3_out1                       : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Gain3_out1_4                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch4_out1_4                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Gain3_out1_3                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch4_out1_3                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Gain3_out1_2                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch4_out1_2                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Gain3_out1_1                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch4_out1_1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Add_out1                         : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Gain3_out1_0                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch4_out1_0                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch4_out1                     : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Switch4_out1_5                   : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Unit_Delay5_bypass_reg           : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Unit_Delay5_out1_1               : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Selector_out1_0                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Selector_out1                    : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL delayMatch2_reg                  : vector_of_std_logic_vector32(0 TO 119);  -- ufix32 [120]
  SIGNAL From1_out1_0                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Add_out1_4                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch_out1_4                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Add_out1_3                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch_out1_3                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Add_out1_2                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch_out1_2                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Add_out1_1                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch_out1_1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch5_out1                     : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Add_out1_0                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch_out1_0                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch_out1                      : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Switch_out1_5                    : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Unit_Delay1_bypass_reg           : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Unit_Delay1_out1_5               : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL Unit_Delay1_out1_6               : vector_of_std_logic_vector32(0 TO 4);  -- ufix32 [5]
  SIGNAL delayMatch3_reg                  : vector_of_std_logic_vector32(0 TO 119);  -- ufix32 [120]
  SIGNAL Unit_Delay1_out1_0               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch5_out1_0                   : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  -- this -1 gain is because the Injection is reversed in the D eqaution

  x_1 <= x;

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch1_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch1_reg(4 DOWNTO 0) <= x_1(4 DOWNTO 0);
        delayMatch1_reg(119 DOWNTO 5) <= delayMatch1_reg(114 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS delayMatch1_process;

  x_2(4 DOWNTO 0) <= delayMatch1_reg(119 DOWNTO 115);

  crp_out_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      gate_1 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        gate_1 <= gate;
      END IF;
    END IF;
  END PROCESS crp_out_delay_process;


  Unit_Delay6_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay6_bypass_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_166_1 = '1' THEN
        Unit_Delay6_bypass_reg <= gate_1;
      END IF;
    END IF;
  END PROCESS Unit_Delay6_bypass_process;

  
  Unit_Delay6_out1 <= gate_1 WHEN enb_1_166_1 = '1' ELSE
      Unit_Delay6_bypass_reg;

  Unit_Delay6_out1_1 <= Unit_Delay6_out1;

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg(4 DOWNTO 0) <= Unit_Delay6_out1_1(4 DOWNTO 0);
        delayMatch_reg(119 DOWNTO 5) <= delayMatch_reg(114 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  Unit_Delay6_out1_2(4 DOWNTO 0) <= delayMatch_reg(119 DOWNTO 115);


  Relational_Operator1_out1_gen: FOR t_0 IN 0 TO 4 GENERATE
    
    Relational_Operator1_out1(t_0) <= '1' WHEN Unit_Delay6_out1_2(t_0) /= gate(t_0) ELSE
        '0';
  END GENERATE Relational_Operator1_out1_gen;



  Logical_Operator_out1_gen: FOR t_01 IN 0 TO 4 GENERATE
    Logical_Operator_out1(t_01) <= x_2(t_01) AND Relational_Operator1_out1(t_01);
  END GENERATE Logical_Operator_out1_gen;


  Logical_Operator_out1_0 <= Logical_Operator_out1(0);

  gate_0 <= gate(0);

  minus_g_1 <= minus_g;

  delayMatch4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      minus_g_2 <= (OTHERS => X"00000000");
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        minus_g_2 <= minus_g_1;
      END IF;
    END IF;
  END PROCESS delayMatch4_process;


  u_nfp_mul_comp_gen: FOR k2 IN 0 TO 4 GENERATE
    u_nfp_mul_comp : nfp_mul_single
      PORT MAP( clk => clk,
                reset => reset,
                enb => enb,
                nfp_in1 => vi_in(k2),  -- ufix32
                nfp_in2 => minus_g_2(k2),  -- ufix32
                nfp_out => Divide_out1(k2)  -- ufix32
                );
  END GENERATE;

  Divide_out1_0 <= Divide_out1(0);

  gate_1_1 <= gate(1);

  Divide_out1_1 <= Divide_out1(1);

  gate_2 <= gate(2);

  Divide_out1_2 <= Divide_out1(2);

  gate_3 <= gate(3);

  Divide_out1_3 <= Divide_out1(3);

  gate_4 <= gate(4);

  Divide_out1_4 <= Divide_out1(4);

  outputgen: FOR k2 IN 0 TO 4 GENERATE
    Xin_idx_unsigned(k2) <= unsigned(Xin_idx(k2));
  END GENERATE;

  Xin_idx_1 <= Xin_idx_unsigned;

  Xin_idx_0 <= Xin_idx_1(0);

  gate_0_1 <= gate(0);

  Divide_out1_0_1 <= Divide_out1(0);

  gate_1_2 <= gate(1);

  Divide_out1_1_1 <= Divide_out1(1);

  gate_2_1 <= gate(2);

  Divide_out1_2_1 <= Divide_out1(2);

  gate_3_1 <= gate(3);

  Divide_out1_3_1 <= Divide_out1(3);

  gate_4_1 <= gate(4);

  Divide_out1_4_1 <= Divide_out1(4);

  Xin_idx_1_1 <= Xin_idx_1(1);

  Xin_idx_2 <= Xin_idx_1(2);

  Xin_idx_3 <= Xin_idx_1(3);

  Xin_idx_4 <= Xin_idx_1(4);

  Logical_Operator_out1_1 <= Logical_Operator_out1(1);

  Logical_Operator_out1_2 <= Logical_Operator_out1(2);

  Logical_Operator_out1_3 <= Logical_Operator_out1(3);

  Logical_Operator_out1_4 <= Logical_Operator_out1(4);

  From1_out1_4 <= From1_out1(4);

  Unit_Delay1_out1_4 <= Unit_Delay1_out1(4);

  
  Switch5_out1_4 <= Unit_Delay1_out1_4 WHEN Logical_Operator_out1_4 = '0' ELSE
      From1_out1_4;

  From1_out1_3 <= From1_out1(3);

  Unit_Delay1_out1_3 <= Unit_Delay1_out1(3);

  
  Switch5_out1_3 <= Unit_Delay1_out1_3 WHEN Logical_Operator_out1_3 = '0' ELSE
      From1_out1_3;

  From1_out1_2 <= From1_out1(2);

  Unit_Delay1_out1_2 <= Unit_Delay1_out1(2);

  
  Switch5_out1_2 <= Unit_Delay1_out1_2 WHEN Logical_Operator_out1_2 = '0' ELSE
      From1_out1_2;

  From1_out1_1 <= From1_out1(1);

  Unit_Delay1_out1_1 <= Unit_Delay1_out1(1);

  
  Switch5_out1_1 <= Unit_Delay1_out1_1 WHEN Logical_Operator_out1_1 = '0' ELSE
      From1_out1_1;

  
  Selector_out1_4 <= Unit_Delay5_out1(0) WHEN Xin_idx_4 = to_unsigned(16#0001#, 16) ELSE
      Unit_Delay5_out1(1) WHEN Xin_idx_4 = to_unsigned(16#0002#, 16) ELSE
      Unit_Delay5_out1(2) WHEN Xin_idx_4 = to_unsigned(16#0003#, 16) ELSE
      Unit_Delay5_out1(3) WHEN Xin_idx_4 = to_unsigned(16#0004#, 16) ELSE
      Unit_Delay5_out1(4);

  
  Selector_out1_3 <= Unit_Delay5_out1(0) WHEN Xin_idx_3 = to_unsigned(16#0001#, 16) ELSE
      Unit_Delay5_out1(1) WHEN Xin_idx_3 = to_unsigned(16#0002#, 16) ELSE
      Unit_Delay5_out1(2) WHEN Xin_idx_3 = to_unsigned(16#0003#, 16) ELSE
      Unit_Delay5_out1(3) WHEN Xin_idx_3 = to_unsigned(16#0004#, 16) ELSE
      Unit_Delay5_out1(4);

  
  Selector_out1_2 <= Unit_Delay5_out1(0) WHEN Xin_idx_2 = to_unsigned(16#0001#, 16) ELSE
      Unit_Delay5_out1(1) WHEN Xin_idx_2 = to_unsigned(16#0002#, 16) ELSE
      Unit_Delay5_out1(2) WHEN Xin_idx_2 = to_unsigned(16#0003#, 16) ELSE
      Unit_Delay5_out1(3) WHEN Xin_idx_2 = to_unsigned(16#0004#, 16) ELSE
      Unit_Delay5_out1(4);

  
  Selector_out1_1 <= Unit_Delay5_out1(0) WHEN Xin_idx_1_1 = to_unsigned(16#0001#, 16) ELSE
      Unit_Delay5_out1(1) WHEN Xin_idx_1_1 = to_unsigned(16#0002#, 16) ELSE
      Unit_Delay5_out1(2) WHEN Xin_idx_1_1 = to_unsigned(16#0003#, 16) ELSE
      Unit_Delay5_out1(3) WHEN Xin_idx_1_1 = to_unsigned(16#0004#, 16) ELSE
      Unit_Delay5_out1(4);

  Gain3_out1_4 <= Gain3_out1(4);

  
  Switch4_out1_4 <= Divide_out1_4_1 WHEN gate_4_1 = '0' ELSE
      Gain3_out1_4;

  Gain3_out1_3 <= Gain3_out1(3);

  
  Switch4_out1_3 <= Divide_out1_3_1 WHEN gate_3_1 = '0' ELSE
      Gain3_out1_3;

  Gain3_out1_2 <= Gain3_out1(2);

  
  Switch4_out1_2 <= Divide_out1_2_1 WHEN gate_2_1 = '0' ELSE
      Gain3_out1_2;

  Gain3_out1_1 <= Gain3_out1(1);

  
  Switch4_out1_1 <= Divide_out1_1_1 WHEN gate_1_2 = '0' ELSE
      Gain3_out1_1;

  u_nfp_uminus_comp_gen: FOR k1 IN 0 TO 4 GENERATE
    u_nfp_uminus_comp : nfp_uminus_single
      PORT MAP( nfp_in => Add_out1(k1),  -- ufix32
                nfp_out => Gain3_out1(k1)  -- ufix32
                );
  END GENERATE;

  Gain3_out1_0 <= Gain3_out1(0);

  
  Switch4_out1_0 <= Divide_out1_0_1 WHEN gate_0_1 = '0' ELSE
      Gain3_out1_0;

  Switch4_out1(0) <= Switch4_out1_0;
  Switch4_out1(1) <= Switch4_out1_1;
  Switch4_out1(2) <= Switch4_out1_2;
  Switch4_out1(3) <= Switch4_out1_3;
  Switch4_out1(4) <= Switch4_out1_4;

  crp_out_delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Switch4_out1_5 <= (OTHERS => X"00000000");
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Switch4_out1_5 <= Switch4_out1;
      END IF;
    END IF;
  END PROCESS crp_out_delay1_process;


  Unit_Delay5_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay5_bypass_reg <= (OTHERS => X"00000000");
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_166_1 = '1' THEN
        Unit_Delay5_bypass_reg <= Switch4_out1_5;
      END IF;
    END IF;
  END PROCESS Unit_Delay5_bypass_process;

  
  Unit_Delay5_out1_1 <= Switch4_out1_5 WHEN enb_1_166_1 = '1' ELSE
      Unit_Delay5_bypass_reg;

  Unit_Delay5_out1 <= Unit_Delay5_out1_1;

  
  Selector_out1_0 <= Unit_Delay5_out1(0) WHEN Xin_idx_0 = to_unsigned(16#0001#, 16) ELSE
      Unit_Delay5_out1(1) WHEN Xin_idx_0 = to_unsigned(16#0002#, 16) ELSE
      Unit_Delay5_out1(2) WHEN Xin_idx_0 = to_unsigned(16#0003#, 16) ELSE
      Unit_Delay5_out1(3) WHEN Xin_idx_0 = to_unsigned(16#0004#, 16) ELSE
      Unit_Delay5_out1(4);

  Selector_out1(0) <= Selector_out1_0;
  Selector_out1(1) <= Selector_out1_1;
  Selector_out1(2) <= Selector_out1_2;
  Selector_out1(3) <= Selector_out1_3;
  Selector_out1(4) <= Selector_out1_4;

  delayMatch2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch2_reg <= (OTHERS => X"00000000");
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch2_reg(0 TO 4) <= Selector_out1(0 TO 4);
        delayMatch2_reg(5 TO 119) <= delayMatch2_reg(0 TO 114);
      END IF;
    END IF;
  END PROCESS delayMatch2_process;

  From1_out1(0 TO 4) <= delayMatch2_reg(115 TO 119);

  From1_out1_0 <= From1_out1(0);

  Add_out1_4 <= Add_out1(4);

  
  Switch_out1_4 <= Divide_out1_4 WHEN gate_4 = '0' ELSE
      Add_out1_4;

  Add_out1_3 <= Add_out1(3);

  
  Switch_out1_3 <= Divide_out1_3 WHEN gate_3 = '0' ELSE
      Add_out1_3;

  Add_out1_2 <= Add_out1(2);

  
  Switch_out1_2 <= Divide_out1_2 WHEN gate_2 = '0' ELSE
      Add_out1_2;

  Add_out1_1 <= Add_out1(1);

  
  Switch_out1_1 <= Divide_out1_1 WHEN gate_1_1 = '0' ELSE
      Add_out1_1;

  u_nfp_sub_comp_gen: FOR k IN 0 TO 4 GENERATE
    u_nfp_sub_comp : nfp_sub_single
      PORT MAP( clk => clk,
                reset => reset,
                enb => enb,
                nfp_in1 => Switch5_out1(k),  -- ufix32
                nfp_in2 => Divide_out1(k),  -- ufix32
                nfp_out => Add_out1(k)  -- ufix32
                );
  END GENERATE;

  Add_out1_0 <= Add_out1(0);

  
  Switch_out1_0 <= Divide_out1_0 WHEN gate_0 = '0' ELSE
      Add_out1_0;

  Switch_out1(0) <= Switch_out1_0;
  Switch_out1(1) <= Switch_out1_1;
  Switch_out1(2) <= Switch_out1_2;
  Switch_out1(3) <= Switch_out1_3;
  Switch_out1(4) <= Switch_out1_4;

  crp_out_delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Switch_out1_5 <= (OTHERS => X"00000000");
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Switch_out1_5 <= Switch_out1;
      END IF;
    END IF;
  END PROCESS crp_out_delay2_process;


  Unit_Delay1_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay1_bypass_reg <= (OTHERS => X"00000000");
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_166_1 = '1' THEN
        Unit_Delay1_bypass_reg <= Switch_out1_5;
      END IF;
    END IF;
  END PROCESS Unit_Delay1_bypass_process;

  
  Unit_Delay1_out1_5 <= Switch_out1_5 WHEN enb_1_166_1 = '1' ELSE
      Unit_Delay1_bypass_reg;

  Unit_Delay1_out1_6 <= Unit_Delay1_out1_5;

  delayMatch3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch3_reg <= (OTHERS => X"00000000");
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch3_reg(0 TO 4) <= Unit_Delay1_out1_6(0 TO 4);
        delayMatch3_reg(5 TO 119) <= delayMatch3_reg(0 TO 114);
      END IF;
    END IF;
  END PROCESS delayMatch3_process;

  Unit_Delay1_out1(0 TO 4) <= delayMatch3_reg(115 TO 119);

  Unit_Delay1_out1_0 <= Unit_Delay1_out1(0);

  
  Switch5_out1_0 <= Unit_Delay1_out1_0 WHEN Logical_Operator_out1_0 = '0' ELSE
      From1_out1_0;

  Switch5_out1(0) <= Switch5_out1_0;
  Switch5_out1(1) <= Switch5_out1_1;
  Switch5_out1(2) <= Switch5_out1_2;
  Switch5_out1(3) <= Switch5_out1_3;
  Switch5_out1(4) <= Switch5_out1_4;

  Hist <= Switch5_out1;

END rtl;

