-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MATE_HDLsolver_myFirstCircuit\PWM_Generator.vhd
-- Created: 2026-03-23 17:18:12
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_Generator
-- Source Path: MATE_HDLsolver_myFirstCircuit/ForFPGA/PWM Generator
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ForFPGA_pkg.ALL;

ENTITY PWM_Generator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_166_0                       :   IN    std_logic;
        enb_1_166_1                       :   IN    std_logic;
        enb                               :   IN    std_logic;
        mod_index                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        steps                             :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        gup                               :   OUT   std_logic;
        glo                               :   OUT   std_logic
        );
END PWM_Generator;


ARCHITECTURE rtl OF PWM_Generator IS

  -- Component Declarations
  COMPONENT Discrete_Triangular_Waveform_Generator
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_166_0                     :   IN    std_logic;
          enb_1_166_1                     :   IN    std_logic;
          enb                             :   IN    std_logic;
          steps                           :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Triangle                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT nfp_relop_single
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nfp_out1                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Discrete_Triangular_Waveform_Generator
    USE ENTITY work.Discrete_Triangular_Waveform_Generator(rtl);

  FOR ALL : nfp_relop_single
    USE ENTITY work.nfp_relop_single(rtl);

  -- Signals
  SIGNAL mod_index_1                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL delayMatch_reg                   : vector_of_std_logic_vector32(0 TO 22);  -- ufix32 [23]
  SIGNAL mod_index_2                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Discrete_Triangular_Waveform_Generator_out1 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Simulink_PS_Converter1           : std_logic;
  SIGNAL Simulink_PS_Converter1_1         : std_logic;

BEGIN
  u_Discrete_Triangular_Waveform_Generator : Discrete_Triangular_Waveform_Generator
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_166_0 => enb_1_166_0,
              enb_1_166_1 => enb_1_166_1,
              enb => enb,
              steps => steps,  -- uint16
              Triangle => Discrete_Triangular_Waveform_Generator_out1  -- single
              );

  u_nfp_relop_comp : nfp_relop_single
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in1 => mod_index_2,  -- single
              nfp_in2 => Discrete_Triangular_Waveform_Generator_out1,  -- single
              nfp_out1 => Simulink_PS_Converter1
              );

  mod_index_1 <= mod_index;

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => X"00000000");
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg(0) <= mod_index_1;
        delayMatch_reg(1 TO 22) <= delayMatch_reg(0 TO 21);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  mod_index_2 <= delayMatch_reg(22);

  gup <= Simulink_PS_Converter1;

  Simulink_PS_Converter1_1 <=  NOT Simulink_PS_Converter1;

  glo <= Simulink_PS_Converter1_1;

END rtl;

