-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MATE_HDLsolver_myFirstCircuit\Set_Reset_Flip_Flop.vhd
-- Created: 2026-03-23 17:18:12
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Set_Reset_Flip_Flop
-- Source Path: MATE_HDLsolver_myFirstCircuit/ForFPGA/PWM Generator/Discrete Triangular-Waveform Generator/Set-Reset 
-- Flip-Flo
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Set_Reset_Flip_Flop IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_166_0                       :   IN    std_logic;
        Set                               :   IN    std_logic;
        Reset_1                           :   IN    std_logic;
        Q                                 :   OUT   std_logic
        );
END Set_Reset_Flip_Flop;


ARCHITECTURE rtl OF Set_Reset_Flip_Flop IS

  -- Component Declarations
  COMPONENT Discrete
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_166_0                     :   IN    std_logic;
          Set                             :   IN    std_logic;
          Reset_1                         :   IN    std_logic;
          Q                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Discrete
    USE ENTITY work.Discrete(rtl);

  -- Signals
  SIGNAL Discrete_out1                    : std_logic;

BEGIN
  u_Discrete : Discrete
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_166_0 => enb_1_166_0,
              Set => Set,
              Reset_1 => Reset_1,
              Q => Discrete_out1
              );

  Q <= Discrete_out1;

END rtl;

