-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\MATE_HDLsolver_myFirstCircuit\Wrap_To_Zero.vhd
-- Created: 2026-03-23 17:18:12
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Wrap_To_Zero
-- Source Path: MATE_HDLsolver_myFirstCircuit/ForFPGA/Counter Free-Running/Wrap To Zero
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Wrap_To_Zero IS
  PORT( U                                 :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        Y                                 :   OUT   std_logic_vector(3 DOWNTO 0)  -- ufix4
        );
END Wrap_To_Zero;


ARCHITECTURE rtl OF Wrap_To_Zero IS

BEGIN
  -- U(k)

  Y <= U;

END rtl;

